export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const PROCESSING_SETUP = "PROCESSING_SETUP";
export const PROCESSING_SETUP_SUCCESS = "PROCESSING_SETUP_SUCCESS";
export const PROCESSING_SETUP_FAIL = "PROCESSING_SETUP_FAIL";
export const PROCESSING_SETUP_RESET = "PROCESSING_SETUP_RESET";

export const LOAD_PROCESSING_REQUEST = "LOAD_PROCESSING_REQUEST";
export const LOAD_PROCESSING_SUCCESS = "LOAD_PROCESSING_SUCCESS";
export const LOAD_PROCESSING_FAIL = "LOAD_PROCESSING_FAIL";


export const COLLECTIONS_SETUP = "COLLECTIONS_SETUP";
export const COLLECTIONS_SETUP_SUCCESS = "COLLECTIONS_SETUP_SUCCESS";
export const COLLECTIONS_SETUP_FAIL = "COLLECTIONS_SETUP_FAIL";
export const COLLECTIONS_SETUP_RESET = "COLLECTIONS_SETUP_RESET";

export const LOAD_COLLECTIONS_REQUEST = "LOAD_COLLECTIONS_REQUEST";
export const LOAD_COLLECTIONS_SUCCESS = "LOAD_COLLECTIONS_SUCCESS";
export const LOAD_COLLECTIONS_FAIL = "LOAD_COLLECTIONS_FAIL";

export const FINANCE_SETUP = "FINANCE_SETUP";
export const FINANCE_SETUP_SUCCESS = "FINANCE_SETUP_SUCCESS";
export const FINANCE_SETUP_FAIL = "FINANCE_SETUP_FAIL";
export const FINANCE_SETUP_RESET = "FINANCE_SETUP_RESET";

export const LOAD_FINANCE_REQUEST = "LOAD_FINANCE_REQUEST";
export const LOAD_FINANCE_SUCCESS = "LOAD_FINANCE_SUCCESS";
export const LOAD_FINANCE_FAIL = "LOAD_FINANCE_FAIL";

export const INFRASTRUCTURE_SETUP = "INFRASTRUCTURE_SETUP";
export const INFRASTRUCTURE_SETUP_SUCCESS = "INFRASTRUCTURE_SETUP_SUCCESS";
export const INFRASTRUCTURE_SETUP_FAIL = "INFRASTRUCTURE_SETUP_FAIL";
export const INFRASTRUCTURE_SETUP_RESET = "INFRASTRUCTURE_SETUP_RESET";

export const LOAD_INFRASTRUCTURE_REQUEST = "LOAD_INFRASTRUCTURE_REQUEST";
export const LOAD_INFRASTRUCTURE_SUCCESS = "LOAD_INFRASTRUCTURE_SUCCESS";
export const LOAD_INFRASTRUCTURE_FAIL = "LOAD_INFRASTRUCTURE_FAIL";


export const HUMAN_RESOURCES_SETUP = "HUMAN_RESOURCES_SETUP";
export const HUMAN_RESOURCES_SETUP_SUCCESS = "HUMAN_RESOURCES_SETUP_SUCCESS";
export const HUMAN_RESOURCES_SETUP_FAIL = "HUMAN_RESOURCES_SETUP_FAIL";
export const HUMAN_RESOURCES_SETUP_RESET = "HUMAN_RESOURCES_SETUP_RESET";

export const LOAD_HUMAN_RESOURCES_REQUEST = "LOAD_HUMAN_RESOURCES_REQUEST";
export const LOAD_HUMAN_RESOURCES_SUCCESS = "LOAD_HUMAN_RESOURCES_SUCCESS";
export const LOAD_HUMAN_RESOURCES_FAIL = "LOAD_HUMAN_RESOURCES_FAIL";

//..............

export const ACTIVITESACH_SETUP = "ACTIVITESACH_SETUP";
export const ACTIVITESACH_SETUP_SUCCESS = "ACTIVITESACH_SETUP_SUCCESS";
export const ACTIVITESACH_SETUP_FAIL = "ACTIVITESACH_SETUP_FAIL";
export const ACTIVITESACH_SETUP_RESET = "ACTIVITESACH_SETUP_RESET";

export const LOAD_ACTIVITESACH_REQUEST = "LOAD_ACTIVITESACH_REQUEST";
export const LOAD_ACTIVITESACH_SUCCESS = "LOAD_ACTIVITESACH_SUCCESS";
export const LOAD_ACTIVITESACH_FAIL    = "LOAD_ACTIVITESACH_FAIL";


export const CIRCULATIONACH_SETUP = "CIRCULATIONACH_SETUP";
export const CIRCULATIONACH_SETUP_SUCCESS = "CIRCULATIONACH_SETUP_SUCCESS";
export const CIRCULATIONACH_SETUP_FAIL    = "CIRCULATIONACH_SETUP_FAIL";
export const CIRCULATIONACH_SETUP_RESET = "CIRCULATIONACH_SETUP_RESET";

export const LOAD_CIRCULATIONACH_REQUEST = "LOAD_CIRCULATIONACH_REQUEST";
export const LOAD_CIRCULATIONACH_SUCCESS = "LOAD_CIRCULATIONACH_SUCCESS";
export const LOAD_CIRCULATIONACH_FAIL    = "LOAD_CIRCULATIONACH_FAIL";



export const FINANCEACH_SETUP = "FINANCEACH_SETUP";
export const FINANCEACH_SETUP_SUCCESS = "FINANCEACH_SETUP_SUCCESS";
export const FINANCEACH_SETUP_FAIL = "FINANCEACH_SETUP_FAIL";
export const FINANCEACH_SETUP_RESET = "FINANCEACH_SETUP_RESET";

export const LOAD_FINANCEACH_REQUEST = "LOAD_FINANCEACH_REQUEST";
export const LOAD_FINANCEACH_SUCCESS = "LOAD_FINANCEACH_SUCCESS";
export const LOAD_FINANCEACH_FAIL    = "LOAD_FINANCEACH_FAIL";


export const PROCESSINGACH_SETUP = "PROCESSINGACH_SETUP";
export const PROCESSINGACH_SETUP_SUCCESS = "PROCESSINGACH_SETUP_SUCCESS";
export const PROCESSINGACH_SETUP_FAIL = "PROCESSINGACH_SETUP_FAIL";
export const PROCESSINGACH_SETUP_RESET = "PROCESSINGACH_SETUP_RESET";

export const LOAD_PROCESSINGACH_REQUEST = "LOAD_PROCESSINGACH_REQUEST";
export const LOAD_PROCESSINGACH_SUCCESS = "LOAD_PROCESSINGACH_SUCCESS";
export const LOAD_PROCESSINGACH_FAIL    = "LOAD_PROCESSINGACH_FAIL";

export const USERSACH_SETUP = "USERSACH_SETUP";
export const USERSACH_SETUP_SUCCESS = "USERSACH_SETUP_SUCCESS";
export const USERSACH_SETUP_FAIL = "USERSACH_SETUP_FAIL";
export const USERSACH_SETUP_RESET = "USERSACH_SETUP_RESET";

export const LOAD_USERSACH_REQUEST = "LOAD_USERSACH_REQUEST";
export const LOAD_USERSACH_SUCCESS = "LOAD_USERSACH_SUCCESS";
export const LOAD_USERSACH_FAIL    = "LOAD_USERSACH_FAIL";

export const TRAININGACH_SETUP = "TRAININGACH_SETUP";
export const TRAININGACH_SETUP_SUCCESS = "TRAININGACH_SETUP_SUCCESS";
export const TRAININGACH_SETUP_FAIL = "TRAININGACH_SETUP_FAIL";
export const TRAININGACH_SETUP_RESET = "TRAININGACH_SETUP_RESET";

export const LOAD_TRAININGACH_REQUEST = "LOAD_TRAININGACH_REQUEST";
export const LOAD_TRAININGACH_SUCCESS = "LOAD_TRAININGACH_SUCCESS";
export const LOAD_TRAININGACH_FAIL   = "LOAD_TRAININGACH_FAIL";


export const GENERALACH_SETUP = "GENERALACH_SETUP";
export const GENERALACH_SETUP_SUCCESS = "GENERALACH_SETUP_SUCCESS";
export const GENERALACH_SETUP_FAIL = "GENERALACH_SETUP_FAIL";
export const GENERALACH_SETUP_RESET = "GENERALACH_SETUP_RESET";

export const LOAD_GENERALACH_REQUEST = "LOAD_GENERALACH_REQUEST";
export const LOAD_GENERALACH_SUCCESS = "LOAD_GENERALACH_SUCCESS";
export const LOAD_GENERALACH_FAIL   = "LOAD_GENERALACH_FAIL";



export const PUBLICATIONACH_SETUP = "PUBLICATIONACH_SETUP";
export const PUBLICATIONACH_SETUP_SUCCESS = "PUBLICATIONACH_SETUP_SUCCESS";
export const PUBLICATIONACH_SETUP_FAIL = "PUBLICATIONACH_SETUP_FAIL";
export const PUBLICATIONACH_SETUP_RESET = "PUBLICATIONACH_SETUP_RESET";

export const LOAD_PUBLICATIONACH_REQUEST = "LOAD_PUBLICATIONACH_REQUEST";
export const LOAD_PUBLICATIONACH_SUCCESS = "LOAD_PUBLICATIONACH_SUCCESS";
export const LOAD_PUBLICATIONACH_FAIL   = "LOAD_PUBLICATIONACH_FAIL";

export const  CURRENT_DATE_SETUP = "CURRENT_DATE_SETUP";