export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const INFRASTRUCTURE_SETUP = "INFRASTRUCTURE_SETUP";
export const INFRASTRUCTURE_SETUP_SUCCESS = "INFRASTRUCTURE_SETUP_SUCCESS";
export const INFRASTRUCTURE_SETUP_FAIL = "INFRASTRUCTURE_SETUP_FAIL";
export const INFRASTRUCTURE_SETUP_RESET = "INFRASTRUCTURE_SETUP_RESET";

export const LOAD_INFRASTRUCTURE_REQUEST = "LOAD_INFRASTRUCTURE_REQUEST";
export const LOAD_INFRASTRUCTURE_SUCCESS = "LOAD_INFRASTRUCTURE_SUCCESS";
export const LOAD_INFRASTRUCTURE_FAIL = "LOAD_INFRASTRUCTURE_FAIL";


export const COLLECTIONS_SETUP = "COLLECTIONS_SETUP";
export const COLLECTIONS_SETUP_SUCCESS = "COLLECTIONS_SETUP_SUCCESS";
export const COLLECTIONS_SETUP_FAIL = "COLLECTIONS_SETUP_FAIL";
export const COLLECTIONS_SETUP_RESET = "COLLECTIONS_SETUP_RESET";

export const LOAD_COLLECTIONS_REQUEST = "LOAD_COLLECTIONS_REQUEST";
export const LOAD_COLLECTIONS_SUCCESS = "LOAD_COLLECTIONS_SUCCESS";
export const LOAD_COLLECTIONS_FAIL = "LOAD_COLLECTIONS_FAIL";


export const  CURRENT_DATE_SETUP = "CURRENT_DATE_SETUP";